FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app

ARG DEEPSEEK_API_KEY
ARG LANGSMITH_API_KEY
ARG LANGSMITH_TRACING
ARG LANGSMITH_PROJECT
ARG LANGSMITH_ENDPOINT
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG MCP_SERVER_URL
ARG MCP_SHARED_SECRET
ARG NEXT_PUBLIC_SITE_URL

ENV DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
ENV LANGSMITH_API_KEY=$LANGSMITH_API_KEY
ENV LANGSMITH_TRACING=$LANGSMITH_TRACING
ENV LANGSMITH_PROJECT=$LANGSMITH_PROJECT
ENV LANGSMITH_ENDPOINT=$LANGSMITH_ENDPOINT
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV MCP_SERVER_URL=$MCP_SERVER_URL
ENV MCP_SHARED_SECRET=$MCP_SHARED_SECRET
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]